// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseDivider: typeof import('./components/BaseDivider.vue')['default']
    BaseHeader: typeof import('./components/BaseHeader.vue')['default']
    BaseLoading: typeof import('./components/BaseLoading.vue')['default']
    BaseTag: typeof import('./components/BaseTag.vue')['default']
    EssayList: typeof import('./components/EssayList.vue')['default']
    EssayListItem: typeof import('./components/EssayListItem.vue')['default']
    EssayTag: typeof import('./components/EssayTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
